BEGIN;

CREATE TABLE accounts (
    id CHAR(42) PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    perms SMALLINT NOT NULL DEFAULT 2,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT perms_check CHECK (perms > 0)
);

COMMIT;
