BEGIN;

CREATE TABLE account_passes (
    id CHAR(42) PRIMARY KEY,
    account_id CHAR(42) NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    pass_id CHAR(42) NOT NULL UNIQUE REFERENCES passes(id) ON DELETE CASCADE,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMIT;
