version: "3.9"
services:
  postgres:
    image: postgres
    restart: unless-stopped
    env_file:
      - ../config/postgres.env.dev
    volumes:
      - postgres:/data/postgres
    ports:
      - "5442:5432"
    networks:
      - postgres
  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    env_file:
      - ../config/pgadmin.env.dev
    volumes:
      - pgadmin:/data/pgadmin
    ports:
      - "5062:80"
    networks:
      - postgres
    depends_on:
      - postgres
  redis:
    image: redis
    restart: unless-stopped
    env_file:
      - ../config/redis.env.dev
    volumes:
      - redis:/data/redis
    ports:
      - "6392:6379"
    networks:
      - redis
networks:
  postgres:
    driver: bridge
  redis:
    driver: bridge
volumes:
  postgres:
  pgadmin:
  redis:
