version: "3.9"
services:
  postgres:
    image: postgres
    container_name: nuclear_postgres
    restart: unless-stopped
    env_file:
      - ../config/postgres.env
    volumes:
      - postgres:/data/postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - postgres
  pgadmin:
    image: dpage/pgadmin4
    container_name: nuclear_pgadmin
    restart: unless-stopped
    env_file:
      - ../config/pgadmin.env
    volumes:
      - pgadmin:/data/pgadmin
    ports:
      - "${PGADMIN_PORT}:80"
    networks:
      - postgres
    depends_on:
      - postgres
  redis:
    image: redis
    container_name: nuclear_redis
    restart: unless-stopped
    command: --requirepass ${REDIS_PASSWORD}
    env_file:
      - ../config/redis.env
    volumes:
      - redis:/data/redis
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - redis
networks:
  postgres:
    driver: bridge
  redis:
    driver: bridge
volumes:
  postgres:
  pgadmin:
  redis:
